### PR TITLE
[Bug] Show vulnerabilities summary in Pod resource list

### LINKED ISSUE #495: [Bug] Vulnerabilities summary missing from Pod resource list
`WorkloadScan` summary column is missing from the main Pod resource list.

Image

### PR DESCRIPTION
**Pull request by rushk014**
FIxes #495

### CODE REVIEW

File: pkg/sbomscanner-ui-ext/utils/workload-scan-report.ts [hunk 1]
```diff
@@ -45,3 +45,60 @@ export function getWorkloadScanReportValue(pod: any) {
     link,
   } as any;
 }
+
+function getPodListId(pod: any): string {
+  return pod?.metadata?.name || pod?.id?.replace(/.*\//, '') || pod?.detailLocation?.params?.id || '';
```
Comment (xingzhang-suse) [inline pkg/sbomscanner-ui-ext/utils/workload-scan-report.ts]: Just a confirmation.
I don't see detailLocation from the pod data. Could you tell me in which case the detailLocation is in the data?
